### Title and directories
scan: 516
alt_id:
year: 2021
exp_id: LauePUP1221
spec_seq: b  # There may be multiple spec files.
beamline: 34idc

### General parameters
calibration: 0
substrate: Si
sample: Au
show_plots: false
verbose: true

### Image prep parameters (all start with "prep_")
prep_quantile: 0.5
prep_gamma: 0.25
prep_rb_radius: # Leave blank to determine automatically
prep_zero_fraction: 0.85
prep_coefficient: 1000
prep_gaussian_sigma: 50

### Peak-indexing parameters (all start with "pkid_")
pkid_substrate_threshold: 10
pkid_substrate_distance: 25
pkid_sample_threshold: 5
pkid_sample_distance: 10

### Laue analysis parameters (all start with "laue_")
laue_substrate_goodness: 0
laue_substrate_mis_err: 0.5
laue_substrate_tolerance: 0.3
laue_substrate_frequency: 0
laue_substrate_comb_sub: 0
laue_substrate_times: 1

laue_sample_goodness: 0
laue_sample_mis_err: 0.5
laue_sample_tolerance: 0.3
laue_sample_frequency: 0
laue_sample_comb_sub: 0
laue_sample_times: 1

grain_tolerance: 0.5
grain_threshold: 10000
