### Title and directories
scan: 147
year: 2021
exp_id: LauePUP1221
alt_id: ""
xtal_params: /home/beams/CXDUSER/34idc-work/2021/LauePUP1221/Analysis/Transfer_to_Sayre_1208/Crystal_Parameters/SrTiO3_crystal_params.json
det_params: /home/beams/CXDUSER/34idc-work/2021/LauePUP1221/Analysis/Transfer_to_Sayre_1208/Detector_Parameters/eiger_params_LauePUP1221_1208_X40Z5.json'

### General parameters
show_plots: false
verbose: true

### Image prep parameters (all start with "prep_")
prep_gamma: 0.25
prep_zero_fraction: 0.85
prep_coefficient: 1000
prep_gaussian_sigma: 50

### Peak-indexing parameters (all start with "pkid_")
pkid_substrate_threshold: 7
pkid_substrate_distance: 25
pkid_sample_threshold: 15
pkid_sample_distance: 14

### Laue analysis parameters (all start with "laue_")
