### Title and directories
scan: 516
year: 2021
exp_id: LauePUP1221
alt_id: ""

### General parameters
substrate: Al2O3
sample: Au
show_plots: true
verbose: true

### Image prep parameters (all start with "prep_")
prep_quantile: 0.01
prep_gamma: 0.25
prep_zero_fraction: 0.85
prep_coefficient: 1000
prep_gaussian_sigma: 50

### Peak-indexing parameters (all start with "pkid_")
pkid_substrate_threshold: 10
pkid_substrate_distance: 25
pkid_sample_threshold: 5
pkid_sample_distance: 10

### Laue analysis parameters (all start with "laue_")
laue_substrate_goodness: 0
laue_substrate_mis_err: 0.5
laue_substrate_tolerance: 0.3
laue_substrate_frequency: 0
laue_substrate_comb_sub: 0
laue_substrate_times: 1

laue_sample_goodness: 0
laue_sample_mis_err: 0.5
laue_sample_tolerance: 0.3
laue_sample_frequency: 0
laue_sample_comb_sub: 0
laue_sample_times: 1

grain_tolerance: 0.5
grain_threshold: 10000

### Detector parameters (all start with "det_")
# TODO have a separate workflow for detector calibration, then read in from output file
det_rotation: [2.235803557314652, -0.011294793963117103, 2.2196066665966945]
det_translation: [-1.5400214690949756, -31.02874070129578, -57.95072572716589]
det_pixels: [1028, 512]
det_pitch: [0.075, 0.075]
det_name: "eiger"
