### Title and directories
scan: 97
alt_id: None
year: 2022
exp_id: LauePUP422
# spec_seq is a unique identifier if there are multiple spec files for the same experiment
spec_seq: b
beamline: 34idc

### General parameters
# Leave calibration blank to select a file manually
calibration: 0
substrate: SrTiO3
sample: Au
show_plots: True
verbose: False

### Image prep parameters (all start with "prep_")
prep_quantile: 0.5
prep_gamma: 1.0
# Leave the rb_radius blank to determine automatically
prep_rb_radius: None
prep_zero_fraction: 0.9
prep_coefficient: 1000
prep_gaussian_sigma: 50

### Peak-indexing parameters (all start with "pkid_")
pkid_substrate_threshold: 0.4
pkid_substrate_distance: 25
pkid_sample_threshold: 0.4
pkid_sample_distance: 10

### Laue analysis parameters (all start with "laue_")
laue_substrate_goodness: 0
laue_substrate_mis_err: 0.5
laue_substrate_tolerance: 0.3
laue_substrate_frequency: 0
laue_substrate_comb_sub: 0
laue_substrate_times: 1

laue_sample_goodness: 0
laue_sample_mis_err: 0.5
laue_sample_tolerance: 0.1
laue_sample_frequency: 0
laue_sample_comb_sub: 0
laue_sample_times: 1

grain_tolerance: 1.0
grain_threshold: 10000

twin_tolerance: 0.1
