### Title and directories
scan: 147
year: 2021
exp_id: LauePUP1221
alt_id: ""
xtal_params: /home/beams/CXDUSER/34idc-work/2021/LauePUP1221/Analysis/Transfer_to_Sayre_1208/Crystal_Parameters/SrTiO3_crystal_params.json
det_params: /home/beams/CXDUSER/34idc-work/2021/LauePUP1221/Analysis/Transfer_to_Sayre_1208/Detector_Parameters/eiger_params_LauePUP1221_1208_X40Z5.json'

### General parameters
show_plots: true
verbose: false

### Image prep parameters (all start with "prep_")
prep_rolling_ball_radius: 50
prep_zero_fraction: 0.85
prep_coefficient: 1000
prep_gaussian_sigma: 50

### Peak-indexing parameters (all start with "pkid_")
pkid_threshold: 3
pkid_min_dist: 25

### Laue analysis parameters (all start with "laue_")
